### ISSUE TITLE
Stadium scenario doesn't work

### ISSUE THREAD

**Issue by ngoduykhanh** [OpenVisualCloud/Smart-City-Sample#216]
I am deploying this sample with both traffic and stadium scenario to a Kubernetes cluster. The traffic scenario works perfectly but the stadium doesn't show anything. There is no sensor available and no video captured. Do you have any idea?

![Screen Shot 2019-11-06 at 10 35 04](https://user-images.githubusercontent.com/6447444/68266264-2a60f580-0081-11ea-8367-1974faf406ad.png)
![Screen Shot 2019-11-06 at 10 34 51](https://user-images.githubusercontent.com/6447444/68266269-2cc34f80-0081-11ea-97d5-b7225d3f6b64.png)

**Comment by ngoduykhanh** [comment]
The stadium's analytic pod is throwing errors. I think it is related to this issue:
`kubectl logs -f stadium-office1-analytics-crowd-7dfbb645b8-mbtqr

ERROR:tornado.access:500 POST /pipelines/crowd_counting/2 (127.0.0.1) 2.41ms
{"levelname": "ERROR", "asctime": "2019-11-06 11:54:01,584", "message": "Error creating destination: {'source': {'uri': 'rtsp://10.203.155.112:17000/live.sdp', 'type': 'uri'}, 'tags': {'sensor': '6u-9Pm4Bp5BYegUhuFH5', 'location': {'lat': 37.38865, 'lon': -121.95405}, 'algorithm': '4--9Pm4Bp5BYegUhr1F4', 'office': {'lat': 37.39856, 'lon': -121.94866}}, 'parameters': {'every-nth-frame': 6, 'recording_prefix': 'recordings/6u-9Pm4Bp5BYegUhuFH5', 'method': 'mqtt', 'address': 'stadium-office1-mqtt-service', 'clientid': '4--9Pm4Bp5BYegUhr1F4', 'topic': 'aad04d00-0651-41a2-adf9-c3df7d473372'}} 'destination'\n", "name": "DestinationTypes"}
ERROR:__main__:Exception on /pipelines/crowd_counting/2 [POST]
Traceback (most recent call last):
  File "/home/video-analytics/app/server/openapi_server/controllers/default_controller.py", line 161, in pipelines_name_version_post
    pipeline_id, err = PipelineManager.create_instance(name, version, connexion.request.get_json())
  File "/home/video-analytics/app/server/openapi_server/../../modules/PipelineManager.py", line 135, in create_instance
    PipelineManager.start()
  File "/home/video-analytics/app/server/openapi_server/../../modules/PipelineManager.py", line 144, in start
    pipeline_to_start.start()
  File "/home/video-analytics/app/server/openapi_server/../../modules/GStreamerPipeline.py", line 206, in start
    self._gst_launch_string = string.Formatter().vformat(self.template, [], self.request)
  File "/usr/lib/python3.6/string.py", line 194, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "/usr/lib/python3.6/string.py", line 234, in _vformat
    obj, arg_used = self.get_field(field_name, args, kwargs)
  File "/usr/lib/python3.6/string.py", line 307, in get_field
    obj = obj[i]
KeyError: 'object_detection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/connexion/decorators/decorator.py", line 73, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.6/dist-packages/connexion/decorators/uri_parsing.py", line 132, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.6/dist-packages/connexion/decorators/validation.py", line 172, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.6/dist-packages/connexion/decorators/validation.py", line 346, in wrapper
    return function(request)
  File "/usr/local/lib/python3.6/dist-packages/connexion/decorators/decorator.py", line 44, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.6/dist-packages/connexion/decorators/parameter.py", line 126, in wrapper
    return function(**kwargs)
  File "/home/video-analytics/app/server/openapi_server/controllers/default_controller.py", line 166, in pipelines_name_version_post
    logger.error('pipelines_name_version_post ' +e)
TypeError: must be str, not KeyError
`

**Comment by xwu2git** [comment]
What you see is expected. The stadium scenario is under development. The models are there but they are not yet connected to the sensors. Expect to update soon.

**Comment by x8091** [comment]
Is camera auto discovery feature (using nmap) complete yet?

**Comment by ngoduykhanh** [comment]
Hi @xwu2git ,

Thanks for the information. I have another question about the map? Is it fixed or we can adjust? I thought we just need to update the `lat` and `lon` in [sensor-info.json](https://github.com/OpenVisualCloud/Smart-City-Sample/blob/master/maintenance/db-init/sensor-info.json) but it seems like not enough. After updating, the map remains the same while building and camera disappeared

I also found another hard-code [here](https://github.com/OpenVisualCloud/Smart-City-Sample/blob/cfd693fff6819373326c8d04c8b7a743495ae1e0/cloud/html/js/scenario.js#L27)

**Comment by xwu2git** [comment]
camera auto discovery is ready. Please see  sensor/README.md.

**Comment by xwu2git** [comment]
Yes, there are three places you need to update:
(1) maintenance/db-init/sensor-info.json.
(2) maintenance/db-init/sensor-info.md,
(3) the scenario.js file you mentioned.

Hold on. I am writing a README on how to extend sensors, offices and MAPs. 
Yes, all are possible to extend including the maps.

**Comment by xwu2git** [comment]
(2) maintenance/db-init/sensor-info.m4

**Comment by x8091** [comment]
> camera auto discovery is ready. Please see sensor/README.md.

I checked already, but it didn't work as expected (The pod `traffic-office1-camera-discovery` didn't output anything related, I changed PORT-RANGE and default username/password already). Maybe my cameras doesn't support ONVIF, but that's not likely. I will double check

BTW, if it works, what should be displayed on UI? Will simulated cameras still there?

**Comment by xwu2git** [comment]
What's your output if you run: PORT_SCAN='-p80-65535 192.168.1.0/24' make discover
If there is no camera detection, then your camera does not support ONVIF.

**Comment by xwu2git** [comment]
It depends on how you modify sensor-info.json. If you still have the simulated camera provisioning info, then simulated and real IP cameras will be displayed together. If you leave only the IP camera identifiers, then only IP cameras will be displayed. 
What happens is that any detected cameras will be compared against this provisioning data and only matched cameras will be displayed in the UI.

**Comment by ngoduykhanh** [comment]
Hi @xwu2git ,

I changed the files you mentioned above. I can see that the object (building, camera) position is changed. But the map isn't loaded. It is just a blank page. Any idea?
![Screen Shot 2019-11-06 at 13 15 56](https://user-images.githubusercontent.com/6447444/68272959-c564ca00-0097-11ea-84c3-50aeb4f4bd75.png)

**Comment by xwu2git** [comment]
Please check out doc/extend.md. You need to build the scenario map, since you move to a different GPS location. The saved map tiles cover only the Hillsboro Oregon area.

**Comment by xwu2git** [comment]
This link might help you get some inner details: https://github.com/Overv/openstreetmap-tile-server.
The entire earth is pretty big, about 80GB of raw data, to be included into a docker container. Only a small portion is extracted as tiles/pngs. 
Let me know if you have issues.
See you tomorrow.

**Comment by ngoduykhanh** [comment]
Hi @xwu2git  

Thanks for the update. I've downloaded the Asia map and tried to use your script to extract data for an area in Singapore with command `./osm_totiles.sh 103.7263 103.7672 1.3097 1.3445`, I also tried with other `lon` and `lat` but the maps always like this. Do you have any idea?

![Screen Shot 2019-11-06 at 16 20 00](https://user-images.githubusercontent.com/6447444/68285435-d9b5c080-00b1-11ea-9319-fe2676004f0d.png)

However, the actual area that I selected from Openstreetmap is like this
![Screen Shot 2019-11-06 at 16 21 30](https://user-images.githubusercontent.com/6447444/68285476-ecc89080-00b1-11ea-9254-864052a4c61c.png)

Have a nice day!

**Comment by xwu2git** [comment]
I tried a smaller version of the pbf: malaysia-singapore-brunei-latest.osm.pbf. 
This is what I got with your parameters: 
![Capture](https://user-images.githubusercontent.com/3871873/68322797-ef5ac400-0078-11ea-8439-df7817bfc772.PNG)
There might be some issues of the osm-tile-server to handle big files. You can workaround by downloading a smaller region. I will check if newer version of the tile server solves this problem.

**Comment by xwu2git** [comment]
After osm_host.sh, you can look at the tile server to see if your map is properly rendered: http://<your-hostname>:8080.

**Comment by ngoduykhanh** [comment]
Thanks @xwu2git , It worked after I rerun the title server with smaller set of pbf malaysia-singapore-brunei-latest.osm.pbf.

**Comment by xwu2git** [comment]
Nice. I could not make the tile server to work with asia.osm.pbf. The latest version also does not work correctly. Probably time to submit a bug against the tile server repo.

**Comment by xwu2git** [comment]
Just FYI. The latest tile server v1.3.8 can render asia.osm.pbf.

**Comment by xwu2git** [comment]
close for now.
