### ISSUE TITLE
how to pass array as input parameter into custom transform

### ISSUE THREAD

**Issue by yimm0815** [OpenVisualCloud/Smart-City-Sample#283]
in crowd counting, currently, i hard coded the polygon in crowd_counting.py as below: 
        self.polygon[0] = [865,210,933,210,933,227,968,227,968,560,934,560,934,568,865,568,865,210]
        self.polygon[1] = [830,49,861,49,893,56,922,71,946,93,960,122,967,151,967,228,934,228,934,211,899,211,867,209,864,183,854,165,836,149,814,144,759,144,759,114,795,114,795,84,830,83,830,49]
        ...

Now i would like to pass the polygon array in sensor database to custom transform in order to calculate the crowd number by each zone

More specifically, how to define the array in pipeline.json? I know single valuable can be defined as below: 
			"width": {
				"element":"detection",
				"type": "integer",
				"minimum": 0,
				"maximum": 4096
			},

**Comment by xwu2git** [comment]
use string and pass a json string or simply comma delimited numbers.

**Comment by nnshah1** [comment]
To pass parameters to a gvapython element add a section to the pipeline parameters that contains a parameter of 'object' type and that targets the 'args' property of the custom element. In the below example we have added the "custom_args" parameter of type object with two properties (width and pointlist). The names of the properties must match the names of the parameters used in the custom transform. 

Illustrative Example (Not Tested):
```
{
  "parameters": {
    "type": "object",
    "properties": {
      "custom_args": {
        "element": {
          "name": "custom",
          "property": "args"
        },
        "type": "object",
        "properties": {
          "width": {
            "type": "integer"
          },
          "pointlist": {
            "type": "array",
            "items": {
              "type": "number"
            }
          }
        }
      }
    }
  }
}
```

**Comment by yimm0815** [comment]
@nnshah1 i set the default input parameters all zero, and validated the actual value cannot pass in still. even with the current pipeline structure you provided. there is one more parameter definition in runva.py. How do i define the custom_args here? 

                "parameters": {
                    "custom_args": {
                        "numZone": 8,
                        "width": resolution["width"],
                        "height": resolution["height"]
                    }
                    "every-nth-frame": every_nth_frame,
                    "recording_prefix": "/tmp/" + sensor,
                },

**Comment by yimm0815** [comment]
Hi, @nnshah1 , things get more complex. For each sensor it may include multiple zones, is it possible to pass list object into custom transform? the zonemap data I want to pass in looks like below: 
zonemap= [
    {"zone": 0, 
    "polygon": [[1080, 200], [1166, 200], [1166, 216], [1211, 216], [1211, 523], [1167, 523], [1167,  530], [1080, 530], [1080, 200]]
    },
    {"zone": 1,
    "polygon": [[1036,51],[1075,51],[1115,58],[1153,72],[1182,92],[1200,119],[1209,146],[1209,216],[1167,216],[1167,201],[1123,201],[1083,199],[1079,175],[1066,159],[1044,144],[1016,139],[946,139],[946,111],[991,111],[991,84],[1036,83],[1036,51]]
    }
]

**Comment by nnshah1** [comment]
I mistakenly left out an additional property needed on the parameters section ,"format":"json" to support object parameters.

I'm attaching a sample pipeline.json with custom element (named 'sample'), a custom transform, and the request. It allows for a list of arbitrary objects to be passed in to the custom transform.
[sample.zip](https://github.com/OpenVisualCloud/Smart-City-Sample/files/3990792/sample.zip)

**Comment by yimm0815** [comment]
Thanks Neelay! Really appreciate!

Thanks,
Mo

On Dec 20, 2019, at 4:17 PM, nnshah1 <notifications@github.com> wrote:

﻿

I mistakenly left out an additional property needed on the parameters section ,"format":"json" to support object parameters.

I'm attaching a sample pipeline.json with custom element (named 'sample'), a custom transform, and the request. It allows for a list of arbitrary objects to be passed in to the custom transform.
sample.zip<https://github.com/OpenVisualCloud/Smart-City-Sample/files/3990792/sample.zip>

**Comment by yimm0815** [comment]
works fine. close the issue
