### ISSUE TITLE
Can GST detection select subset of object types

### ISSUE THREAD

**Issue by yimm0815** [OpenVisualCloud/Smart-City-Sample#285]
we need people detection result in queue counting, current we use ssd model which detect any object type. Be aware of that we use object detection pipeline for queue counting, so we don't have custom transform in the pipeline. What's the best way to constraint the result to people only?

**Comment by nnshah1** [comment]
Currently the gvadetect element is designed to return all objects detected within a frame that meet a configurable threshold of confidence. 

To count only the objects of a certain type, there are two current options:

1) Post process the JSON message in the application. That is the application that receives the MQTT message from the pipeline can parse the message and remove non relevant items

2) Add a gvapython custom transform into the pipeline to act as a "filter" before metaconvert / metapublish element. The gvapython custom transform can add / remove objects before the JSON Message is created.

Both options are viable for this use case and I don't believe they would have a huge difference in performance. Option 1 leaves the video pipeline unaffected, but increases (slightly) the logic needed in the application. Option 2 places the bulk of the logic directly in the pipeline and the pipeline performance should be validated again.

**Comment by yimm0815** [comment]
i prefer to take option 1, not to increase a extra pipeline element. because the docker image is shared between object detection in traffic and queue counting in smartstadium, I would like to keep pipeline as similar as possible. if we use same model, then pipeline for both case could merge together.

**Comment by yimm0815** [comment]
switch from ssd model to person detection model https://github.com/OpenVisualCloud/Smart-City-Sample/commit/fe8c2bbe5ede6fe381876da1442b3adb1ada5850. this issue doesn't exist anymore. let's close it.
