### ISSUE TITLE
Try person detection model from open model zoo

### ISSUE THREAD

**Issue by dahanhan** [OpenVisualCloud/Smart-City-Sample#288]
The model below can generate person bounding boxes only:
https://download.01.org/opencv/2019/open_model_zoo/R3/20190905_163000_models_bin/person-detection-retail-0013/FP32/person-detection-retail-0013.xml
https://download.01.org/opencv/2019/open_model_zoo/R3/20190905_163000_models_bin/person-detection-retail-0013/FP32/person-detection-retail-0013.bin

**Comment by yimm0815** [comment]
thanks! @dahanhan Is the model-proc.json the same as well?

**Comment by dahanhan** [comment]
@yimm0815 The model-proc.json should be changed to only output person bounding box:
            _"labels":["person"],_

**Comment by dahanhan** [comment]
Since the label id of the new models is 1 for the person class, the file model-proc.json should add a blank label before 'person' as below:
_"labels":["","person"],_

**Comment by yimm0815** [comment]
thanks. will try it today. if success, please add FP16 and INT8 as well. :)

**Comment by yimm0815** [comment]
tried the person-detection model, in the two sample videos, one has actual 7 people, but two of them are scored at 67% and 68%, we take 70% as threshold if i am not wrong. could you raise the bar?

**Comment by dahanhan** [comment]
As described on https://github.com/opencv/gst-video-analytics/wiki/gvadetect, a 'threshold' property of gvadetect can control the inference threshold. its default value should be 0.5. We can set it in corresponding pipeline.json.
Did you see the person scored at 67% is not detectable?

**Comment by dahanhan** [comment]
Models of other precisions:
FP16:
https://download.01.org/opencv/2019/open_model_zoo/R3/20190905_163000_models_bin/person-detection-retail-0013/FP16/person-detection-retail-0013.xml
https://download.01.org/opencv/2019/open_model_zoo/R3/20190905_163000_models_bin/person-detection-retail-0013/FP16/person-detection-retail-0013.bin
INT8:
https://download.01.org/opencv/2019/open_model_zoo/R3/20190905_163000_models_bin/person-detection-retail-0013/INT8/person-detection-retail-0013.xml
https://download.01.org/opencv/2019/open_model_zoo/R3/20190905_163000_models_bin/person-detection-retail-0013/INT8/person-detection-retail-0013.bin

**Comment by yimm0815** [comment]
thanks! model updated in https://github.com/OpenVisualCloud/Smart-City-Sample/commit/fe8c2bbe5ede6fe381876da1442b3adb1ada5850
