### ISSUE TITLE
Add crowd counting BKM

### ISSUE THREAD

**Issue by dahanhan** [OpenVisualCloud/Smart-City-Sample#291]
@xwu2git I can't directly edit wiki page, and not able fork the wiki repo. So I have to copy original wiki  pages and add crowd counting BKM on another wiki repo: https://github.com/dahanhan/Smart-City-Sample.wiki.git . Can you help to merge it to here? Thanks.

**Comment by dahanhan** [comment]
It's OK to upload BKM in wiki page

**Comment by xwu2git** [comment]
Edited. Please check.
