### ISSUE TITLE
The project is missing the processing method when disk is full

### ISSUE THREAD

**Issue by zongxin1993** [OpenVisualCloud/Smart-City-Sample#334]
When  disk is full , in the WEB UI  no warning  and  alert . The system will take up more and more space then the system has an error for this reason.

**Comment by xwu2git** [comment]
Committed a fix on master. There are multiple levels of disk usage controls:
(1) The disk usage level is warned at WARN_DISK, and fatal at FATAL_DISK and recording halted at HALT_REC in deployment/docker-swarm/office-storage.m4,cloud-storage.m4 or deployment/kubernetes/office-storage.yaml.m4,cloud-storage.yaml.m4.
(2) There are periodical recording cleanups of old records (disk & database) controlled by the RETENTION_TIME in the above scripts.
