### ISSUE TITLE
detailed design page should be able to access from smart city wiki as well

### ISSUE THREAD

**Issue by yimm0815** [OpenVisualCloud/Smart-City-Sample#351]
some overlapped design between ad insertion and smart city, i only see from ad insertion wiki page, such as kafka, nginx, tornado,etc. since customers don't know they are connected together, ovc team should at least provide some links between these two projects, or provide separate design diagram is also ok.

**Comment by xwu2git** [comment]
Design is described in https://github.com/OpenVisualCloud/Smart-City-Sample/wiki#introduction.
