### ISSUE TITLE
No rule to make target 'start_openness_camera

### ISSUE THREAD

**Issue by illuri-537** [OpenVisualCloud/Smart-City-Sample#541]
Hi Team,

while i am  running the command make start_openness_camera in camera simualtor.

i was getting error like this  "make: *** No rule to make target 'start_openness_camera'.  Stop."

So when I do make help , i  observed  that there is no target like "start_openness_camera".
![make_help](https://user-images.githubusercontent.com/36484257/86783969-96678380-c07e-11ea-962c-2adf9cd3dae2.png)

**Comment by xwu2git** [comment]
I see that you are running the master code. There is no make_openness_camera there.

Please see this link for starting/stopping multiple offices under OpenNESS:
https://github.com/OpenVisualCloud/Smart-City-Sample/blob/master/deployment/kubernetes/helm/smtc/README.md#multiple-office-startstop

cameras are integrated into 'offices'. They don't have a dedicated target at this point.

**Comment by xwu2git** [comment]
Sorry, this link instead: https://github.com/OpenVisualCloud/Smart-City-Sample/blob/master/deployment/kubernetes/helm/smtc/README.md#multiple-cluster-setup
