### ISSUE TITLE
Unable to getting the office  nodes and cameras in Web UI

### ISSUE THREAD

**Issue by illuri-537** [OpenVisualCloud/Smart-City-Sample#542]
Hi,

I am not able to see the office nodes and cameras in webUI after the sucessfully deployed smart city on the cloud cluster  openness cluster and camera simulator machine.

**Comment by xwu2git** [comment]
Please check the camera-discovery module logs. 
Make sure the cameras can be detected.

**Comment by ishanVshah** [comment]
Hi, I am facing the same issue. and logs of both offices may be correct.

/usr/bin/nmap -p T:17000-17050 192.168.1.10 -Pn -n
/usr/bin/nmap -p T:17000-17050 192.168.1.10 -Pn -n
/usr/bin/nmap -p T:17000-17050 192.168.1.10 -Pn -n
^C

[root@zd03 build]# kubectl logs -f traffic-office2-camera-discovery-6bf8c78cb4-f8b5b
/usr/bin/nmap -p T:18000-18050 192.168.2.10 -Pn -n
/usr/bin/nmap -p T:18000-18050 192.168.2.10 -Pn -n

**Comment by xwu2git** [comment]
Please attach all logs.

**Comment by ishanVshah** [comment]
@xwu2git  
thanks a lot for your response.
[Intel_2020-07-21_11-43-49.log](https://github.com/OpenVisualCloud/Smart-City-Sample/files/4951654/Intel_2020-07-21_11-43-49.log)

please find attached all camera pods logs.

**Comment by ishanVshah** [comment]
Hi @xwu2git 

I appreciate if you help me because i have this openness infra for limited time period.

**Comment by xwu2git** [comment]
I wonder how did you even get to this logs.

If your intention is to run the samples with simulated cameras, then the nmap scanning command should not have 192.168.1.10 or 192.168.2.10. The IP address should be the corresponding camera container POD. Did you modify the Kubernetes yaml or helm files?

If your intention is to run the samples with IP camreas, then the nmap command line should have -P 80-65535 instead of -p T:17000-17050, as this range is used for simulated cameras.

Can you revert to the original master code and restart the sample?

**Comment by xwu2git** [comment]
You don't have simulated camera services running in your pod list. So I guess you try to detect the IP cameras. Have you followed sensor/README.md to setup the IP cameras?

**Comment by ishanVshah** [comment]
Hi @xwu2git 

no, I followed below links to setup OVC/SmartCity on Network Edge OpenNESS 20.06.

in that case, cameras are working as a docker container which is separate machine.

https://www.openness.org/docs/doc/applications-onboard/network-edge-applications-onboarding
https://github.com/OpenVisualCloud/Smart-City-Sample/tree/openness-k8s/deployment/openness

I didn't change anything other than that.

camera docker container logs are attached.
[docker_camera_logs.JPG.log](https://github.com/OpenVisualCloud/Smart-City-Sample/files/4955011/docker_camera_logs.JPG.log)

**Comment by ishanVshah** [comment]
svc screenshot:
![image](https://user-images.githubusercontent.com/59759055/88084851-9e591480-cba2-11ea-8183-514c019bbbf3.png)

smart-city web-page:
![image](https://user-images.githubusercontent.com/59759055/88084914-b3ce3e80-cba2-11ea-88f5-df6c60cb5d78.png)

**Comment by xwu2git** [comment]
Can you login into the camera discovery POD, and check if there is a network interface called 192.168.1.0/24?
ip link list.

**Comment by ishanVshah** [comment]
Hi @xwu2git 
ip link list command is not found and not able to install ip-utils package using yum manager.

below some output of the pods may be helpful.
---------------------------------------------------------------------------------------------------
[root@traffic-office1-camera-discovery-fb6f6fb65-hpv4b ~]# cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
10.16.0.54	traffic-office1-camera-discovery-fb6f6fb65-hpv4b
--------------------------------------------------------------------------------------
[root@traffic-office1-camera-discovery-fb6f6fb65-hpv4b ~]# env
HOSTNAME=traffic-office1-camera-discovery-fb6f6fb65-hpv4b
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT=tcp://10.96.0.1:443
TERM=xterm
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_HOST=10.96.0.1
NO_PROXY=*
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
LD_LIBRARY_PATH=:/usr/local/lib:/usr/local/lib64
SIM_PREFIX=cams1o1c
DBHOST=http://traffic-office1-db-service:9200
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
OFFICE=45.539626,-122.929569
PWD=/root
SERVICE_INTERVAL=30
SHLVL=1
HOME=/root
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
no_proxy=*
SIM_PORT=17000/17010/17020/17030/17040/
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
PORT_SCAN=-p T:17000-17050 192.168.1.10 -Pn
_=/usr/bin/env
OLDPWD=/etc/sysconfig

--------------------------------------------------------------------------------
[root@traffic-office1-camera-discovery-fb6f6fb65-hpv4b ~]# cat /etc/resolv.conf 
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
-----------------------------------------------------------------------------------------

**Comment by xwu2git** [comment]
Most likely you don't have access to the 192.168.1.x network from the POD.
Have you setup the data planes in the discovery and analytics POD?

**Comment by sgarg18** [comment]
After doing the complete set up of Kubernetes cluster and following the procedure as given in kubernetes/README.md. When i run kubectl get pods commnad, i am getting ImagePullBackOff status. How to retify this problem

**Comment by xwu2git** [comment]
The ImagePullBackOff error indicates that your built images are not distributed any private registry your cluster uses. 
Do you have a private docker registry in your setup? If yes, use cmake -DREGISTRY=... and make again. The images will be pushed to the registry after the build. 
If you don't have a private docker registry, run make update after the build. The images will be copied to each worker node assuming you have passwordless access from the controller node to the worker nodes.
