### ISSUE TITLE
Not Able to Establish Connection between db.service and camera-discovery

### ISSUE THREAD

**Issue by illuri-537** [OpenVisualCloud/Smart-City-Sample#548]
Hi,

I am unable to get the offices and camera in UI, When i got the logs of camera- discovery ,  I am getting Exception like this
![db service](https://user-images.githubusercontent.com/36484257/87903031-00a2ff80-ca53-11ea-824a-6a0adad6d318.PNG)

Can you please help me.

**Comment by xwu2git** [comment]
Do you see any analytics output? Do you see any line that connects the camera and the building becomes green? Do you see a chart icon above the sensor icon? If so, then analytics run ok. You can ignore the exception, which usually occurs at the startup stage where each container starts at different time.

**Comment by xwu2git** [comment]
Can you check the cloud-db logs? Is database up and running?

**Comment by illuri-537** [comment]
Now Camera and office is working in Web UI but analytics is not happening
![analytics1](https://user-images.githubusercontent.com/36484257/88044345-f0b81800-cb45-11ea-9d53-eafaa131c219.PNG)

can you please check

**Comment by xwu2git** [comment]
What did you do to make camera discovery work? Do you have any network policy in place on the system? If so, please remove them. From the message description, it looks like the RTSP URL is blocked in the analytics instance.

**Comment by xwu2git** [comment]
or firewall?

**Comment by illuri-537** [comment]
can we deploy smart city with one office node?

**Comment by illuri-537** [comment]
we configured dbhost as cloud host Ip then cameraand office is showing Web UI.

**Comment by xwu2git** [comment]
yes, you can.
