### ISSUE TITLE
cannot build image with V20.4 branch

### ISSUE THREAD

**Issue by lvcarry** [OpenVisualCloud/Smart-City-Sample#588]
Branch: v20.4
OS: Centos7.6
Build failed with following log:

Step 6/14 : RUN git clone ${VA_SERVING_REPO} -b ${VA_SERVING_BRANCH} --depth 1
 ---> Running in c1b819f011cb
Cloning into 'video-analytics-serving'...
warning: Could not find remote branch v0.3_preview to clone.
**fatal: Remote branch v0.3_preview not found in upstream origin**
The command '/bin/sh -c git clone ${VA_SERVING_REPO} -b ${VA_SERVING_BRANCH} --depth 1' returned a non-zero code: 128
make[2]: *** [analytics/common/CMakeFiles/build_smtc_analytics_common] Error 1
make[1]: *** [analytics/common/CMakeFiles/build_smtc_analytics_common.dir/all] Error 2
make: *** [all] Error 2

**Comment by QuPengfei** [comment]
try the https://github.com/OpenVisualCloud/Smart-City-Sample/pull/589

**Comment by lvcarry** [comment]
Still failed with this change but error is different:

Step 8/10 : COPY --from=build /home/video-analytics-serving/vaserving /home/vaserving
COPY failed: stat /var/lib/docker/overlay2/bd552c1d04f04af52f517b9721015f872b5ad8329feaaa5b70c7f709b8bfb43c/merged/home/video-analytics-serving/vaserving: no such file or directory
make[2]: *** [analytics/common/CMakeFiles/build_smtc_analytics_common] Error 1
make[1]: *** [analytics/common/CMakeFiles/build_smtc_analytics_common.dir/all] Error 2
make: *** [all] Error 2

**Comment by QuPengfei** [comment]
update the patch

**Comment by lvcarry** [comment]
It works with updated patch.
Thx for quick response.
