### ISSUE TITLE
[SMTC]Offices and cameras are lost once reboot worker node after k8s setup

### ISSUE THREAD

**Issue by lvcarry** [OpenVisualCloud/Smart-City-Sample#606]
Test commit: latest master branch, 
   https://github.com/OpenVisualCloud/Smart-City-Sample/commit/0d2ceb263688d68a13c933d5396f760b813b34d8

Steps:
1.Enable "SMTC" based on k8s .
2. Check all pods status and check the web with https://master_node_ip. Ensure they are all working as expected.
3. Then run "reboot" in worker node and check step 2 again, after all pods are created and running again.
You'll find the web can only show map but no offices and cameras info.
This issue isn't reproduced if reboot master node.

**Comment by xwu2git** [comment]
Fixed at master. 
The db-init task needs to rerun upon a node lost and recovery (actually, when db is restarted.)
The db-init task is initially designed as a job and it never restarts upon completion.
Converting db-init to a deployment does the trick.

**Comment by xwu2git** [comment]
Not really the final solution yet, as db-init isn't tied to the database POD. db-init must be tied to the database POD so any db-restarting will restart the corresponding db-init.

**Comment by lvcarry** [comment]
I filed this bug based on master.

**Comment by xwu2git** [comment]
There are fixes on the master to address this issue. Please try the tip of the master branch.

**Comment by lvcarry** [comment]
Test with latest commit: commit 1003314449b57cf7303100b892924043493a2737 

The behavior is changed:

cluster is ready and reboot "minion node"
Then run "kubelet get nodes" to find "minon node" is " notready" now although all pods status are still running. 
And if you open URL and you'll find "the website cannot be accessed.
so at least, the url and kubelet log are compatible.
