### ISSUE TITLE
specify and/or check docker version installed 

### ISSUE THREAD

**Issue by mathieuduperre** [OpenVisualCloud/Smart-City-Sample#655]
There is no check for specific docker version. The node I tried was on an older docker release and I ended up getting this error:

Error parsing reference: "centos:7.6.1810 as build" is not a valid repository/tag: invalid reference format

removing the old docker release and upgrading it to 1.19 fixed this problem. There should be a docker version check to validate you are on the the expected one. I don't remember seeing a required version # in the readme (my bad if its there).

**Comment by xwu2git** [comment]
Thanks for the suggestion. Will add the check.

**Comment by xwu2git** [comment]
What version did you have?

**Comment by mathieuduperre** [comment]
I "think" it was 1.13.  the one you get with centos7 if you do not force update the docker repo. You need to manually force the repo update and remove docker before reinstalling with a specific release. It dependes on your version of K8.
