### ISSUE TITLE
Fail to run webrtc pods and no video recording in camera

### ISSUE THREAD

**Issue by lvcarry** [OpenVisualCloud/Smart-City-Sample#689]
Commit: 3ce4ad287b43ec4dc722002a7dfc1522a7a5aee9
Run deployment and then check pods and url.  following pods are failed. But you can see map/office if you open URL, but cannot see any "recording" video if you click on the cameras.

traffic-office1-webrtc-748c54c75d-vzv2s 2/3 **CrashLoopBackOff** 11 34m
traffic-office2-webrtc-74d495b64-6dfng 2/3 **CrashLoopBackOff** 11 34m
Then check the pod log:
kubectl  logs traffic-office2-webrtc-5d77694c84-lr8nq -c webrtc
{
        "databases" : [
                {
                        "name" : "admin",
                        "sizeOnDisk" : 8192,
                        "empty" : false
                },
                {
                        "name" : "local",
                        "sizeOnDisk" : 8192,
                        "empty" : false
                },
                {
                        "name" : "owtdb",
                        "sizeOnDisk" : 16384,
                        "empty" : false
                }
        ],
        "totalSize" : 32768,
        "ok" : 1
}
mongodb connected successfully
Initializing ManagementAPIServer configuration...
superServiceId: 5f840524d636910017835cd1
superServiceKey: ZemX/1wCvjj+ms0l9546B9GZu/ZOk6063kAWIz8s+lBIpW9u5J56LKERUW03oUvpbnlXwUBnb6c5CtyCT5Xf41plSKdy6IJcR2SoWERFN3wEj6xCPImR3zXTJHkCF4sN0Larc2u8GGQ5SJPm4cpt9MdPVqje/tzhPgPLgMPryi0=
sampleServiceId: 5f840524d636910017835cd2
sampleServiceKey: OK5iaQUOvJRei/5qz8vLTHiz3EIKsq/zO/Xez63K/7EiUJXTxmTQTCdPQrUstuDg9dgv0N30yHIMdHkuW1mbL/IAk0dP4s5aqKA8vum0Ls7lNsQ0NtsCWHPiNzoByipMew7CEHoCSZklgVHG2PdOo0lvzEAML/YIy0wZr7NIxlA=
Error in saving configuration: { Error: EACCES: permission denied, open '/home/owt/management_api/management_api.toml'
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/home/owt/management_api/management_api.toml' }
{ Error: EACCES: **permission denied, open '/home/owt/extras/basic_example/samplertcservice.js'**
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/home/owt/extras/basic_example/samplertcservice.js' }
sed: couldn't open temporary file **/home/seduWjzcK: Permission denied**

**Comment by lvcarry** [comment]
This is SMTC regression. I revert smtc to old commit 2c60fb657f1ea7c46c8f737cb1e913c6294f8d9d and all pods are running . url video is also OK.

BTW, webrtc pods are new pods which is not in old commit.
![image](https://user-images.githubusercontent.com/45352264/95718462-136b5000-0ca1-11eb-8de1-afb3ff22fd2f.png)
![image](https://user-images.githubusercontent.com/45352264/95718483-1cf4b800-0ca1-11eb-8529-fb6eaa039727.png)

**Comment by xwu2git** [comment]
I think this is the issue of building as root vs. as a regular user. Fixing...

**Comment by xwu2git** [comment]
Fixed.

**Comment by lvcarry** [comment]
Run with latest STMC commit cfb98001a43f0742717c546332396526c1bbbd99 and it passed:
![Uploading image.png…]()
