### ISSUE TITLE
Issue in make

### ISSUE THREAD

**Issue by ppnaik1890** [OpenVisualCloud/Smart-City-Sample#721]
I get the following error when I do make. Can you please help me resolve it. Thanks!

`Step 5/15 : COPY --from=smtc_common /home/*.py /home/
invalid from flag value smtc_common: pull access denied for smtc_common, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

**Comment by PengfeiQu** [comment]
Please check smtc_common image is built successfully. it is not from docker hub.

**Comment by QuPengfei** [comment]
Please check smtc_common image is built successfully. it is not from docker hub.

**Comment by ppnaik1890** [comment]
It looks like it was successfully built. THis was in the logs before the error occured:
`Built target build_smtc_common`

**Comment by goanto** [comment]
@QuPengfei @ppnaik1890 
I am also facing the same error
![image](https://user-images.githubusercontent.com/27364117/104409035-6a780e00-558b-11eb-8e7c-998fb4ef34aa.png)

Its happening only while the make reaches /sensor/simlation/Dockerfile.
![image](https://user-images.githubusercontent.com/27364117/104409931-57663d80-558d-11eb-94a0-b705e278ce8a.png)

For another image creation in make from smtc_common it's working fine.
![image](https://user-images.githubusercontent.com/27364117/104409158-a7440500-558b-11eb-8cb1-6d91701c8b8e.png)

**Comment by xwu2git** [comment]
Is this issue still valid? 
I did a fresh pull and fresh re-make, twice. 
Could not reproduce this build error.
Checked sensor/* dependencies, The dependency on common is correctly specified.
