### ISSUE TITLE
Sending local index to cloud-db

### ISSUE THREAD

**Issue by divdaisymuffin** [OpenVisualCloud/Smart-City-Sample#740]
Hi @xwu2git, In the multioffice scenario, we have 4 indexes in the cloud-db-0, i.e. sensors, recordings, offices and analytics, similarly I want algorithm index into the cloud-db-0. Till now, I know that runva.py and for traffic scenario detect_objcet.py ingest the data using dbingest by importing db_ingest.py. So, I Tried somethings around them, now I have algorithm index initialized into the cloud-db-0, but it contains no docs.

Please help me in this. Thanks

**Comment by xwu2git** [comment]
The two functions you need to use the [db_ingest::ingest](https://github.com/OpenVisualCloud/Smart-City-Sample/blob/master/common/db_ingest.py) and [db_query:search](https://github.com/OpenVisualCloud/Smart-City-Sample/blob/master/common/db_query.py). You can use the search function to extract the docs in the local office algorithm index and then ingest into the cloud_db index.

**Comment by xwu2git** [comment]
You can also refer to the [smart upload](https://github.com/OpenVisualCloud/Smart-City-Sample/blob/master/maintenance/smart-upload/smart-upload.py) feature.
