### ISSUE TITLE
The command line option FRAMEWORK does not actually change to  ffmpeg

### ISSUE THREAD

**Issue by sudhirkshirsagar** [OpenVisualCloud/Smart-City-Sample#755]
Does gst even when ffmpeg is specified. The console build output shows that.
Documentation says FRAMEWORK: Specify the target framework: gst or ffmpeg , Now gst is enabled.

**Comment by xwu2git** [comment]
FFmpeg as an analytics framework was initially planned. There is some technical difficulty to implement it, mostly around time stamps. So this is never finished. Only gst is supported for now. Please do not use ffmpeg as a framework. I will remove it from the config.

**Comment by xwu2git** [comment]
Fixed.

**Comment by sudhirkshirsagar** [comment]
Apart from fixing the command line option, the documentation on how to add
new mp4 files needs to be revised. That still uses the ffmpeg command.
