### ISSUE TITLE
Can multiple Office with "stadium" scenario ?

### ISSUE THREAD

**Issue by AustynTang** [OpenVisualCloud/Smart-City-Sample#774]
Hi,

I encountered a problem when deploying with "stadium" scenario,  but my environment is not exists, so I  describe the problem in words.. : )

 When in "traffic" scenario:
**cmake -DPLATFORM=XXX -DSCENARIO=traffic-DNOFFICES=2 -DNCAMERAS=2 -DNANALYTICS=2 -DFRAMEWORK=XXX
make
SCOPE=office1 CONNECTOR_CLOUD=test@cloudserver make start_helm
SCOPE=office2 CONNECTOR_CLOUD=test@cloudserver make start_helm**
Two office node(s) helm installation result is "deployed", and kubectl get pod and svc is "running".

But in "stadium" scenario:
**cmake -DPLATFORM=XXX-DSCENARIO=stadium -DNOFFICES=2 -DNCAMERAS=2 -DNANALYTICS=2 -DFRAMEWORK=XXX
make
SCOPE=office1 CONNECTOR_CLOUD=test@cloudserver make start_helm
SCOPE=office2 CONNECTOR_CLOUD=test@cloudserver make start_helm**
Office1 can be deployed, but regardless of whether office1 has been deployed office2 always fails to install.

And office2 helm debug result is "helm Error: no objects visited".

It seem like to the helm chart recourses not be created with the file in template folder,  if helm uninstall stadium-office2-* it says"0 Resource has been deleted", and I watch the helm/smtc/template/YAML_FILES, there will be some if condition judgments at the beginning of the file, is it caused by these conditions?

Then if I use "traffic" scenario to start office2, it can start, is it related to some other configurations? Thanks!

**Comment by xwu2git** [comment]
Stadium does not support multiple offices. Precisely speaking, it does. But the second stadium is not defined in the sample. To define a new stadium, you need to define new GPS location, a new stadium map. See [extending maps](https://github.com/OpenVisualCloud/Smart-City-Sample/blob/master/doc/extend.md).

**Comment by AustynTang** [comment]
@xwu2git Thanks so much for response！
