### ISSUE TITLE
We want to get recieved FPS of the running analytics pod sensor.

### ISSUE THREAD

**Issue by divdaisymuffin** [OpenVisualCloud/Smart-City-Sample#786]
We want to get recieved FPS of the running analytics pod sensor, as we are getting processed fps in the algorithm index via runva.py.
Please Suggest how we cn proceed.

**Comment by xwu2git** [comment]
db=DBQuery(host, "algorithms", office)
r=list(db.search("_id={}".format(algorithm_id), size=1)
print(r[0]["_source"], flush=True)

**Comment by xwu2git** [comment]
If you want to search by sensor_id:

db=DBQuery(host, "algorithms", office)
r=list(db.search("sensor='{}'".format(sensor_id), size=1))
print(r[0]["_source"], flush=True)

**Comment by nnshah1** [comment]
@divdaisymuffin Beyond looking at the frame rate supplied by the camera and looking at the incoming PTS we don't have a ready solution for determining the incoming (network) framerate seperate from the processing framerate without further instrumenting the pipeline.

**Comment by divdaisymuffin** [comment]
@nnshah1 okay we will proceed with that
