### ISSUE TITLE
Problem with inference of YOLOv4 model at openvisualcloud

### ISSUE THREAD

**Issue by divdaisymuffin** [OpenVisualCloud/Smart-City-Sample#794]
Hi @nnshah1 @xwu2git 

We need help with inference of yolov4 model at Smart-City-Sample, the same model we are successfully running at openvino, I am attaching error I am getting.
![Screenshot from 2021-11-08 12-13-14](https://user-images.githubusercontent.com/68895288/140741562-32b438cb-fc4b-4e23-a2fc-c41f599f80a4.png)

The model proc I am using is at [model-proc](https://github.com/openvinotoolkit/dlstreamer_gst/blob/master/samples/model_proc/public/object_detection/yolo-v4-tf.json)

The raw model file and converted IR file you can find at [Model](https://drive.google.com/drive/u/0/folders/1N4Lo7A5agMN_Ejc7_54qpi3zv_j_APCM)

We have also tried publicly available yolov4 model but with that also the error is same, Does openvisualcloud do not support YOLOv4?

**Comment by divdaisymuffin** [comment]
Hi @nnshah1 @xwu2git,
I am updating about the trial of yolov4 inference on latest Smart-City-Sample, and it also failed with same error.
We have tried yolov4-tiny as well but it also ended with same error logs.

**Comment by nnshah1** [comment]
@divdaisymuffin I was able to run the model locally with a latest version of DL Streamer but I didn't see any inference results generated. Do you have sample image / video I could use to confirm?

**Comment by divdaisymuffin** [comment]
@nnshah1 You can find the v4_tiny.py Inference script, input.mp4 and v4_tiny_output.avi file in this link
https://drive.google.com/drive/u/0/folders/1N4Lo7A5agMN_Ejc7_54qpi3zv_j_APCM

**Comment by dsmertin** [comment]
@divdaisymuffin 
Now we have good tutorial: https://github.com/openvinotoolkit/dlstreamer_gst/wiki/How-to-create-model-proc-file
You can use it to build model-proc for your model (our model-proc files are not common and they appropriate one concrete model).

For your model should be good follow model-proc file:
```js
{
    "json_schema_version": "2.0.0",
    "input_preproc": [],
    "output_postproc": [
      {
        "converter": "tensor_to_bbox_yolo_v3",
        "iou_threshold": 0.4,
        "anchors": [10.0, 14.0, 23.0, 27.0, 37.0, 58.0, 81.0, 82.0, 135.0, 169.0, 344.0, 319.0],
        "masks": [3, 4, 5, 1, 2, 3],
        "classes": 80
      }
    ]
  }
  ```

**Comment by divdaisymuffin** [comment]
@dsmertin Thanks a lot, let me try this.

**Comment by dsmertin** [comment]
Hi @divdaisymuffin 

Еverything is fine, сan we close this issue?

**Comment by divdaisymuffin** [comment]
@dsmertin yes we can close this, it is working fine.
