### ISSUE TITLE
Larger Recordings are not getting transferred to storage pod

### ISSUE THREAD

**Issue by divdaisymuffin** [OpenVisualCloud/Smart-City-Sample#798]
Hi @nnshah1

As we discussed on previous issue thread [issue link](https://github.com/OpenVisualCloud/Smart-City-Sample/issues/797)

The larger recording is now getting created at analytics pod but it is not getting transfered to storage pod, and hence on gui as well we see no recording.

**Comment by xwu2git** [comment]
This might be related to the `client_max_body_size` and [`upload_max_file_size`](https://www.nginx.com/resources/wiki/modules/upload/#upload-max-file-size) values. Please adjust those in the storage pod `nginx.conf` file.

**Comment by divdaisymuffin** [comment]
@xwu2git It is working fine now. Thanks a lot.
