### ISSUE TITLE
Custom model's model proc shows layer name issue

### ISSUE THREAD

**Issue by divdaisymuffin** [OpenVisualCloud/Smart-City-Sample#802]
Hi @nnshah1

We are stuck with model proc of custom trained model, we have created our own network and trained it and converted it into IR format, now we are trying to import it to the Smart-City-Sample and also created one model-proc for the same using your guide, still we are getting error with the "layer name" for output layer.

Please find the [model and model-proc](https://drive.google.com/drive/folders/1t3YHSACucUBxqNqFBtLuw2Koq_aDX0UU) here.
Please find logs attached.
[logs.txt](https://github.com/OpenVisualCloud/Smart-City-Sample/files/7617995/logs.txt)

**Comment by divdaisymuffin** [comment]
@nnshah1 we have successfully deployed with change to latest version plus change in model-proc. 
Also noticed that with latest update CPU utilisation is much less.

**Comment by nnshah1** [comment]
Thanks @divdaisymuffin I'll assume this issue is closed.
