### ISSUE TITLE
frame.message() return empty in process_frame when there isn't any detected object within the frame

### ISSUE THREAD

**Issue by dhaval-zala-aivid** [OpenVisualCloud/Smart-City-Sample#811]
Hii @nnshah1

When the frame.message() is empty the rest postprocessing is not working because we used len(frame.message()) > 0 as a main condition. Actually, when we are processing past-video file as a sensor, we need to use some parameters such as **real_base, resolution, and office** to calculate the past frame time and these parameters can be received from frame.message() only. So, how can we get all those parameters in process_frame when frame.message() is empty?

**Comment by nnshah1** [comment]
in the pipeline - on the gvametaconvert element you can use the property: add-empty-results=true

This should generate empty metadata for every frame - can  you check if that meets your needs?

**Comment by dhaval-zala-aivid** [comment]
Yes, it works!
 
Thank You!
